---
- name: Deploy nginx
  hosts: webservers
  remote_user: runner
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

  - name: Nginx install
    apt:
        name: nginx-extras
        state: latest
        update_cache: true

  - name: Check SHA hash local index file
    stat:
        path: ./index.html
        checksum_algorithm: sha1

    delegate_to: localhost
    register: local_stat
    become: no

  - name: Check SHA hash remote index file
    stat:
        path: /var/www/html/index.html
        checksum_algorithm: sha1
    register: remote_stat

  - name: Copy sample index file if differs
    copy:
        src: ./index.html
        dest: /var/www/html/index.html
        force: yes
        mode: 0644
    when: local_stat.stat.checksum != remote_stat.stat.checksum
    notify: Restart nginx

  - name: Debug
    debug:
        msg: "{{local_stat.stat.checksum}} {{remote_stat.stat.checksum}}"

  - name: Ensure Nginx is running
    systemd:
        name: nginx
        state: started
    register: nginx_state

  handlers:

  - name: Restart nginx
    systemd:
          name: nginx
          state: restarted
          daemon_reload: true
    register: restart_nginx_result
    ignore_errors: true

